### ISSUE TITLE
venn_diagram error

### ISSUE THREAD

**Issue by summerghw** [vloux/ProteoRE#284]
hi, i was trying to reanlasis "**_Annotating a protein list identified by LC-MS/MS experiments_**" in galaxy training materials. at last step, a error occur , `Traceback (most recent call last):
  File "/home/galaxy/galaxy/database/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_venn_diagram/e744a43171ff/proteore_venn_diagram/venn_diagram.py", line 187, in <module>
    process( args )
  File "/home/galaxy/galaxy/database/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_venn_diagram/e744a43171ff/proteore_venn_diagram/venn_diagram.py", line 171, in process
    write_summary(args.summary, args.input)
  File "/home/galaxy/galaxy/database/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_venn_diagram/e744a43171ff/proteore_venn_diagram/venn_diagram.py", line 151, in write_summary
    write_text_venn(data)
  File "/home/galaxy/galaxy/database/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_venn_diagram/e744a43171ff/proteore_venn_diagram/venn_diagram.py", line 116, in write_text_venn
    result = dict((k, v) for k, v in json_result["data"].iteritems() if v != [])
AttributeError: 'dict' object has no attribute 'iteritems'`
could you help. thanks a lot

**Comment by yvandenb** [comment]
@summerghw : thx for your feedback; please could you share or send us the link of your history in which it happens so that we can reproduce this issue ?

**Comment by summerghw** [comment]
sorry for reply so late, this error apears when i try to repeat the "Annotating a protein list identified by LC-MS/MS experiments" and "Biomarker candidate identification" workflow in [https://training.galaxyproject.org/](url) tool versiong was Venn diagram [JVenn] (Galaxy Version 2020.01.10)  , i was trying to use this three files as input [https://zenodo.org/record/3405119/files/Lacombe_2018.txt](url) [https://zenodo.org/record/3405119/files/Bredberg.txt](url) [https://zenodo.org/record/3405119/files/Mucilli.txt](url)

**Comment by yvandenb** [comment]
Thx for reply: please again, can you share or send us the link of your history in which it happens so that we can reproduce this issue ? To share this link from your Galaxy Account:  click on the "Share or Publish" menu from the History panel options, and copy/paste the link displayed here

**Comment by yvandenb** [comment]
no answer from @summerghw - unable to reproduce the bug on our side - issue closed
