### ISSUE TITLE
JVenn Bug : proteore.org

### ISSUE THREAD

**Issue by yvandenb** [vloux/ProteoRE#315]
History: http://www.proteore.org/u/yvdb/h/ovariancortex
Version tool used: Venn diagram [JVenn] (Galaxy Version 2021.05.12)
Same bug observed using Venn diagram [JVenn] (Galaxy Version 2020.01.10) 
NB: each list contains > 6500 entries

Traceback (most recent call last):
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_venn_diagram/e744a43171ff/proteore_venn_diagram/venn_diagram.py", line 187, in <module>
    process( args )
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_venn_diagram/e744a43171ff/proteore_venn_diagram/venn_diagram.py", line 171, in process
    write_summary(args.summary, args.input)
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_venn_diagram/e744a43171ff/proteore_venn_diagram/venn_diagram.py", line 149, in write_summary
    a, b = input_to_dict(inputs)
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_venn_diagram/e744a43171ff/proteore_venn_diagram/venn_diagram.py", line 57, in input_to_dict
    file_content = [x for x in [line[int(ncol.replace("c", ""))-1].split(";") for line in file_content[1:]]]     # gets ids from defined column
IndexError: list index out of range

**Comment by vloux** [comment]
Reproducible.
Empty lines in input files are not filtered and make Jvenn fail.

Should the tool fltered it without launching an error or should the error be explicit ?

**Comment by yvandenb** [comment]
>Should the tool fltered it without launching an error
I would vote for this solution

**Comment by yvandenb** [comment]
Not a bug in itself, rather an improvement => carriage return or linefeed in the list of entries should normally be removed...
